/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import Controlador.ControladorReportes;

/**
 *
 * @author Esteban Canto Vázquez
 */
public class FrmBuscarComprobante extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmBuscarComprobante
     */
    public FrmBuscarComprobante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlIngresarNumeroDeFactura = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lbFactura = new javax.swing.JLabel();
        lbMostrarFactura = new javax.swing.JLabel();
        lbFechaDeVenta = new javax.swing.JLabel();
        lbMostrarFechaDeVenta = new javax.swing.JLabel();
        pnlDatosCliente = new javax.swing.JPanel();
        lbNombres = new javax.swing.JLabel();
        lbApellidoPaterno = new javax.swing.JLabel();
        lbApellidoMaterno = new javax.swing.JLabel();
        lbMostrarNombres = new javax.swing.JLabel();
        lbMostrarApellidoPaterno = new javax.swing.JLabel();
        lbMostrarApellidoMaterno = new javax.swing.JLabel();
        lbProductos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        lbIVA = new javax.swing.JLabel();
        lbMostrarIVA = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbMostrarTotal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("BuscarComprobante");

        pnlIngresarNumeroDeFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Numero de Factura"));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIngresarNumeroDeFacturaLayout = new javax.swing.GroupLayout(pnlIngresarNumeroDeFactura);
        pnlIngresarNumeroDeFactura.setLayout(pnlIngresarNumeroDeFacturaLayout);
        pnlIngresarNumeroDeFacturaLayout.setHorizontalGroup(
            pnlIngresarNumeroDeFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarNumeroDeFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlIngresarNumeroDeFacturaLayout.setVerticalGroup(
            pnlIngresarNumeroDeFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarNumeroDeFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngresarNumeroDeFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        lbFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbFactura.setText("Factura N°:");

        lbMostrarFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrarFactura.setText("...");

        lbFechaDeVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbFechaDeVenta.setText("Fecha de Venta:");

        lbMostrarFechaDeVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrarFechaDeVenta.setText("...");

        pnlDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));

        lbNombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNombres.setText("Nombres:");

        lbApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbApellidoPaterno.setText("Ap.Paterno:");

        lbApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbApellidoMaterno.setText("Ap.Materno:");

        lbMostrarNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrarNombres.setText("...");

        lbMostrarApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrarApellidoPaterno.setText("...");

        lbMostrarApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrarApellidoMaterno.setText("...");

        javax.swing.GroupLayout pnlDatosClienteLayout = new javax.swing.GroupLayout(pnlDatosCliente);
        pnlDatosCliente.setLayout(pnlDatosClienteLayout);
        pnlDatosClienteLayout.setHorizontalGroup(
            pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombres)
                    .addComponent(lbMostrarNombres))
                .addGap(57, 57, 57)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbApellidoPaterno)
                    .addComponent(lbMostrarApellidoPaterno))
                .addGap(37, 37, 37)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMostrarApellidoMaterno)
                    .addComponent(lbApellidoMaterno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosClienteLayout.setVerticalGroup(
            pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidoPaterno)
                    .addComponent(lbNombres)
                    .addComponent(lbApellidoMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMostrarApellidoPaterno)
                    .addComponent(lbMostrarApellidoMaterno)
                    .addComponent(lbMostrarNombres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbProductos.setText("Productos");

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbProductos);

        lbIVA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIVA.setText("IVA:");

        lbMostrarIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrarIVA.setText("...");

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotal.setText("Total:");

        lbMostrarTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrarTotal.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbProductos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMostrarFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbFechaDeVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMostrarFechaDeVenta))
                            .addComponent(pnlDatosCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlIngresarNumeroDeFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbIVA)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTotal)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMostrarTotal)
                            .addComponent(lbMostrarIVA))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlIngresarNumeroDeFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFactura)
                    .addComponent(lbMostrarFactura)
                    .addComponent(lbFechaDeVenta)
                    .addComponent(lbMostrarFechaDeVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIVA)
                    .addComponent(lbMostrarIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal)
                    .addComponent(lbMostrarTotal))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Controlador.ControladorReportes objetoReporte = new ControladorReportes();
        objetoReporte.BuscarFacturaMostrarDatosCliente(txtBuscar, lbMostrarFactura, lbMostrarFechaDeVenta, lbMostrarNombres, lbMostrarApellidoPaterno, lbMostrarApellidoMaterno);
        objetoReporte.BuscarFacturaMostrarDatosProductos(txtBuscar, tbProductos, lbMostrarIVA, lbMostrarTotal);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarComprobante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbApellidoMaterno;
    private javax.swing.JLabel lbApellidoPaterno;
    private javax.swing.JLabel lbFactura;
    private javax.swing.JLabel lbFechaDeVenta;
    private javax.swing.JLabel lbIVA;
    private javax.swing.JLabel lbMostrarApellidoMaterno;
    private javax.swing.JLabel lbMostrarApellidoPaterno;
    private javax.swing.JLabel lbMostrarFactura;
    private javax.swing.JLabel lbMostrarFechaDeVenta;
    private javax.swing.JLabel lbMostrarIVA;
    private javax.swing.JLabel lbMostrarNombres;
    private javax.swing.JLabel lbMostrarTotal;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbProductos;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel pnlDatosCliente;
    private javax.swing.JPanel pnlIngresarNumeroDeFactura;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
